apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: go-unagasvm
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/rhtap_qe/go-unagasvm:50a3a3d2e0b32760fd8bd099d81c4fd1d82892d4@sha256:9773634b5e19397c3cd7514f770be7a78bdd2ba2924f6df0489121c63c859e28
        name: container-image  
